name: CI
on:
  workflow_dispatch:
   inputs:
      tag:
          description: 'tag or sha to run job on'
          required: true
          default: ''
  release:
    types: [published]
  push:
    branches:
      - main
    tags:
      - '*'  
jobs:
  test-github-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ contains(github.event_name, 'release') }}
        uses: actions/checkout@v2

      - name: Checkout
        if: ${{ contains(github.event_name, 'workflow_dispatch') }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: docker image tags
        id: tags
        env:
          EVENT: ${{ github.event_name }}
        run: |
          IMAGE=ghcr.io/bilelkhalsi/ioservices/service-db-migration
          REF=${{ github.sha }}
          TAGS="${IMAGE}:${REF}"
          if [$EVENT == 'release']
          then
            RELEASE=${{ github.event.release.tag_name }}
            TAGS="${TAGS},${IMAGE}:${RELEASE},${IMAGE}:latest"
            echo "Release event : ${RELEASE}"
          elif [ $EVENT == 'workflow_dispatch' ]
          then
            TAG=${{ github.event.inputs.tag }}
            TAGS="${TAGS},${IMAGE}:${TAG}"
            echo "Manually running on tag  : ${TAG}"
          else
            echo " Push event : ${REF}"
          fi
          echo ::set-output name=tags::${TAGS}

      - name: Show Github Event  
        env:
          github: ${{ toJSON(github) }}
          event: ${{ toJSON(github.event) }}
          tags:  ${{ steps.tags.outputs.tags }}
        run: |
          echo $tags
          
